#!/usr/bin/env ruby
require 'github_api'
require 'optparse'

def display_repos(repos)
  repos.each do |repo|
    puts repo.name
  end
end

APP_NAME = File.basename $PROGRAM_NAME

options = {
  archived:      false,
  forked:        false,
  only_archived: false,
  only_forked:   false,
}

OptionParser.new do |opts|
  opts.banner = <<-ENDOFUSAGE
    #{APP_NAME} queries the given user or organisations repositories
    and displays information about them.

      $ #{APP_NAME} --user deanwilson
      ...
      TODO
      alexa-skill-registered-domain
      alexa-skill-webstatuscode
      ...
  ENDOFUSAGE

  opts.on('-a', '--archived',
          'include archived repositories in the output.') { |v| options[:archived] = v }

  opts.on('-f', '--fork',
          'include forked repositories in the output.') { |v| options[:fork] = v }

  opts.on('--only-archived',
          'only include archived repositories in the output.') { |v| options[:only_archived] = v }

  opts.on('--only-forked',
          'only include forked repositories in the output.') { |v| options[:only_forked] = v }

  opts.on('-u', '--user USER',
          'github user to query.') { |user| options[:user] = user || ARGV[0] }

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
end.parse!

if options[:user].nil?
  if ARGV[0]
    options[:user] = ARGV[0]
  else
    puts 'Please supply a github username'
    exit 1
  end
end

config = {
  auto_pagination: true,
  token:           ENV['GITHUB_TOKEN'],
  user:            options[:user],
}

## do not allow multiple exclusive flags
enabled_exclusives = options.select {|k,v| k.to_s.start_with? 'only_' and v }.keys
if enabled_exclusives.length > 1
  puts "#{APP_NAME}: only one 'only_' option can be supplied"
  exit 1
end


github = Github.new oauth_token: config[:token]

repos = github.repos.list(config).to_a

if options[:only_archived]
  repos.select! { |r| r.archived }
  display_repos(repos)
  exit
end

if options[:only_forked]
  repos.select! { |r| r.fork }
  display_repos(repos)
  exit
end


# ignore non-source repos by default.
repos.reject! { |r| r.archived } unless options[:archived]
repos.reject! { |r| r.fork } unless options[:forked]


display_repos(repos)
